image: $CONTAINER_TEST_IMAGE

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME

stages:
  - build_docker
  - testing
  - build_tarballs

build_docker:
  image: docker
  stage: build_docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test_gcc:
  stage: testing
  script:
    - python3 setup.py sdist
    - 'tar xvzf sdist/ducc0*.tar.gz'
    - 'cd ducc0-* && python3 setup.py install --user -f && pytest-3 -q python/test'

test_clang:
  stage: testing
  script:
    - python3 setup.py sdist
    - 'tar xvzf sdist/ducc0*.tar.gz'
    - 'cd ducc0-* && CC="clang -fsized-deallocation" python3 setup.py install --user -f && pytest-3 -q python/test'

release:
  stage: build_tarballs
  script:
    - python3 setup.py sdist
    - 'mv dist/*.tar.gz .'
  artifacts:
    paths:
      - '*.tar.gz'
