image: $CONTAINER_TEST_IMAGE

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  OMP_NUM_THREADS: 2

stages:
  - build_docker
  - testing
  - build_tarballs

build_docker:
  image: docker:19.03.8
  stage: build_docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test_cxxbase:
  stage: testing
  script:
    - python3 setup.py install --user -f
    - pytest-3 -q test

test_cxxbase_clang:
  stage: testing
  script:
    - CC="clang -fsized-deallocation" python3 setup.py install --user -f
    - pytest-3 -q test

release:
  stage: build_tarballs
  script:
    - python3 setup.py sdist
  artifacts:
    paths:
      - '*.tar.gz'
