language: python

python:
  - 3.7

os:
  - linux
  
dist:
  - focal

compiler:
  - gcc-9

matrix:
  include:
    - name: "Python 3.7 on MacOSX 10.15"
      os: osx
      osx_image: xcode12
      language: shell
    - name: "Python 3.7 on MacOSX 10.14"
      os: osx
      osx_image: xcode10.2
      language: shell

cache:
  apt: true

addons:
  apt:
    update: true
  homebrew:
    update: true

before_install:
  - pip3 install pytest

install:
  - python3 setup.py install

script:
  - pytest python/test

