name: ducc-tests
on: [push]
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install --user --upgrade setuptools pybind11 pytest pytest-timeout
      - run: python setup.py install --user --prefix=
      - run: python -m pytest python/test/test_sht.py python/test/test_totalconvolve.py
